<a href="https://colab.research.google.com/github/random-words/colab-notebooks/blob/main/00__tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Creating tensors with `tf.constant`

In [3]:
# Import TenforFlow
import tensorflow as tf
print(tf.__version__)

2.17.1


In [4]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
# Check the number of dimentions (ndim)
scalar.ndim

0

In [6]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# Check the number of dimentions for vector
vector.ndim

1

In [8]:
# Create a matrix (more than 1 dimention)
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Check the number of dimentions for matrix
matrix.ndim

2

In [10]:
# Create another matrix
another_matrix = tf.constant([[1., 2.],
                              [3., 4.],
                              [5., 6.]], dtype=tf.float16) # specify the data dype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [11]:
another_matrix.ndim

2

In [12]:
# Create tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [13]:
# Check ndim
tensor.ndim

3

### Creating tensors with `tf.Variable`

In [14]:
changable_tensor = tf.Variable([10, 7])
unchangable_tensor = tf.constant([10, 7])

changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [16]:
# Indexes just like in arrays
changable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [18]:
# Trying to change value "on place"
changable_tensor[0] = 7
changable_tensor[0]

TypeError: 'ResourceVariable' object does not support item assignment

In [19]:
# using .assign method
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [21]:
# Cannot assign value in any way
unchangable_tensor[0].assign(7)
unchangable_tensor[0] = 7

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

### Creating random tensors

In [24]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle tensor

In [25]:
# Create tensor
not_shuffled = tf.constant([[1, 2], [3, 4], [5, 6]])

# Shuffle tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [1, 2],
       [5, 6]], dtype=int32)>

In [94]:
tf.random.set_seed(42) # global level seed
tf.random.shuffle(not_shuffled, seed=42) # operation level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [77]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [5, 6],
       [3, 4]], dtype=int32)>

### Other ways to make tensors

In [95]:
# "all ones" tensor
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [96]:
# "all zeroes" tensor
tf.zeros((3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

Main difference is that tensors can run on GPU (for faster numerical computing)

In [99]:
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [105]:
# convert numpy array into tensor
A = tf.constant(numpy_A, shape=(2, 3, 4)) # convert to 3 dimentions
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [107]:
tf.constant(numpy_A, shape=(3, 8))

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [108]:
A.ndim

3

### Tensor attributes

Popular attributes:
* Shape
* Rank
* Axis or dimention
* Size

In [111]:
# Create rank 4 dimentions
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [112]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [113]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [116]:
print("Datatype of each element:", rank_4_tensor.dtype)
print("Number of dimentions (rank):", rank_4_tensor.ndim)
print("Tensor's shape:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Totan number of tensors:", tf.size(rank_4_tensor))
print("Totan number of tensors as numpy type:", tf.size(rank_4_tensor).numpy())

Datatype of each element: <dtype: 'float32'>
Number of dimentions (rank): 4
Tensor's shape: (2, 3, 4, 5)
Elements along axis 0 of tensor: 2
Elements along last axis of tensor: 5
Totan number of tensors: tf.Tensor(120, shape=(), dtype=int32)
Totan number of tensors as numpy type: 120


### Indexing tensors

Indexation as Python lists

In [117]:
some_list = [1,2,3,4]
some_list[:2]

[1, 2]

In [124]:
# get the first 2 elements of each dimentions
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [125]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [127]:
rank_4_tensor[:1, :1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 1), dtype=float32, numpy=array([[[[0.]]]], dtype=float32)>

In [128]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [129]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [135]:
# Create rank 2 tensor (2 dimentions)
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4]])
rank_2_tensor, rank_2_tensor.shape, rank_2_tensor.ndim

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 TensorShape([2, 2]),
 2)

In [136]:
# Last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [138]:
# Add an extra dimention to rank_2_tensor
# '...' - means all of the axes, and we add new axis to them in the end
# '[..., tf.newaxis]' is the same as '[:, :, tf.newaxis]'
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [140]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # '-1' means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [142]:
tf.expand_dims(rank_2_tensor, axis=0) # expand 0-axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]]], dtype=int32)>

In [144]:
# which axis (or index, if talking about shape) is specified, is inserted there
tf.expand_dims(rank_2_tensor, axis=1) # expand 1-axis

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[1, 2]],

       [[3, 4]]], dtype=int32)>

### Tensor operations

**Basic operations:**
`+`, `-`, `*`, `/`,

In [146]:
# Adding
tensor = tf.constant([[1, 2],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14]], dtype=int32)>

In [147]:
# Muiltiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [148]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-9, -8],
       [-7, -6]], dtype=int32)>

In [149]:
# Can use built-in functions too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [150]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

### Matrix multiplication

**Numbers on the `inside` must match (3x`3` <---> `3`x2)**

**New size is the same as outer numbers (3x2, because `3`x3 <---> 3x`2`)**

In [151]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [152]:
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [154]:
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [157]:
# '@' in Python for matrix multiplication
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [159]:
# Create matrix in shape (3, 2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
# Create another matrix in shape (3, 2)
Y = tf.constant([[11, 12],
                 [13, 14],
                 [15, 16]])

X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14],
        [15, 16]], dtype=int32)>)

In [160]:
# Try to matrix multiply matrices with the same shape
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [168]:
# Try to matrix multiply matrices with .matmul
tf.matmul(X, Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [169]:
# Transpose use
tf.transpose(Y)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 13, 15],
       [12, 14, 16]], dtype=int32)>

In [165]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 35,  41,  47],
       [ 81,  95, 109],
       [127, 149, 171]], dtype=int32)>

In [166]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[11, 12],
       [13, 14],
       [15, 16]], dtype=int32)>

In [171]:
# Or reshape (more correct option)
tf.reshape(Y, (2, 3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)>

In [172]:
X.shape, tf.reshape(Y, (2, 3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [170]:
X @ tf.reshape(Y, (2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]], dtype=int32)>

In [176]:
tf.matmul(X, tf.reshape(Y, (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]], dtype=int32)>

In [177]:
tf.reshape(X, (2, 3)).shape, Y.shape

(TensorShape([2, 3]), TensorShape([3, 2]))

In [175]:
# Changing shape of X instead of Y
tf.matmul(tf.reshape(X, (2, 3)), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 82,  88],
       [199, 214]], dtype=int32)>

In [178]:
# Again, transpose
X, tf.transpose(X), tf.reshape(X, (2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [179]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[125, 134],
       [164, 176]], dtype=int32)>

**The Dot Product (Matrix Multiplication)**

* `tf.matmul()`
* `tf.tensordot()`
* `@`

In [180]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[11, 12],
        [13, 14],
        [15, 16]], dtype=int32)>)

In [193]:
# Transposing X
tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[125, 134],
       [164, 176]], dtype=int32)>

In [196]:
# Transposing Y
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 35,  41,  47],
       [ 81,  95, 109],
       [127, 149, 171]], dtype=int32)>

In [197]:
# Reshaping Y
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  42,  45],
       [ 89,  96, 103],
       [139, 150, 161]], dtype=int32)>

In [198]:
# if needed to choose reshaping or transposing, usually choose transposing

### Changing datatype of a tensor

In [205]:
# Create tensor with float datatype
B = tf.constant([1.7, 2.5])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 2.5], dtype=float32)>,
 tf.float32)

In [206]:
C = tf.constant([2, 3])
C.dtype

tf.int32

In [207]:
# Change from float32 to float16 (this is called "reduced precision")
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 2.5], dtype=float16)>,
 tf.float16)

In [211]:
# Change from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [212]:
E_float16 = tf.cast(C, dtype=tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([2., 3.], dtype=float16)>

### Aggregating tensors

In [214]:
# Get the absolute value
tensor = tf.constant([-7, -10])
tf.abs(tensor)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [215]:
tensor = tf.constant(np.random.randint(0, 100, size=50))
tensor

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([75, 39, 48, 28, 51, 62, 47, 21, 13, 82,  7, 22, 11, 26, 49, 75, 43,
       32,  5, 16, 48,  3, 37, 95, 66, 85, 12, 30, 72, 57, 47, 84,  4, 35,
       85,  6,  1, 35,  9, 66, 83, 56, 96, 30, 50, 40, 76, 12, 70, 49])>

In [216]:
tf.size(tensor), tensor.shape, tensor.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [217]:
# Find minimum
tf.reduce_min(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [218]:
# Find maximum
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [219]:
# Find mean
tf.reduce_mean(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [220]:
# Find sum
tf.reduce_sum(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=2191>

In [224]:
# Find variance
tf.math.reduce_variance(tf.cast(tensor, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=747.5>

In [231]:
# Find standard deviation
tf.math.reduce_std(tf.cast(tensor, dtype=tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.34>

In [226]:
# Or using tensorflow_probability
import tensorflow_probability as tfp

In [227]:
tfp.stats.variance(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=748>

### Finding positional maximuim and minimum

In [234]:
tf.random.set_seed(42)
tensor = tf.random.uniform([50])
tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [235]:
# Find the positional maximum (index with a most higher value)
tf.argmax(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [236]:
np.argmax(tensor)

42

In [237]:
tensor[tf.argmax(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [238]:
# Find the max value of "tensor"
tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [239]:
tensor[tf.argmax(tensor)] == tf.reduce_max(tensor)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [240]:
# Find positional minimum
tf.argmin(tensor)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [241]:
# Find minimum using index
tensor[tf.argmin(tensor)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimentions)

In [243]:
tf.random.set_seed(42)
tensor = tf.constant(tf.random.uniform([50]), shape=(1,1,1,1,50))
tensor

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [244]:
tensor.shape

TensorShape([1, 1, 1, 1, 50])

In [246]:
squeezed_tensor = tf.squeeze(tensor)
squeezed_tensor, squeezed_tensor.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [255]:
some_list = [0, 1, 2, 3] # representation of some colors

tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

### Squaring, log, square root

In [257]:
tensor = tf.range(1, 10)
tensor

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [258]:
tensor ** 2

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [259]:
# degree of 2
tf.square(tensor)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [263]:
# sqrt
tf.sqrt(tf.cast(tensor, tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [264]:
# log
tf.math.log(tf.cast(tensor, tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

### Tensors and NumPy

In [265]:
tensor_np = tf.constant(np.array([3., 7., 10.]))
tensor_np

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [266]:
# Convert tensor to NumPy array
np.array(tensor_np), type(np.array(tensor_np))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [267]:
# Convert tensor using method
tensor_np.numpy(), type(tensor_np.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [269]:
tensor_np.numpy()[0]

3.0

In [270]:
# Default dtypes are different
numpy_tensor = tf.constant(np.array([3., 7., 10.]))
tensor = tf.constant([3., 7., 10.])

numpy_tensor.dtype, tensor.dtype

(tf.float64, tf.float32)

### Access to GPU

In [1]:
import tensorflow as tf

tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi

Tue Jan 21 00:28:59 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8              12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--